export type Tool = {
    tool_name?: string;
    bit_width: number;
    spindle_speed: number;
    feed_rate: number;
    step_down: number;
    plunge_feed_rate: number;
};
export type FourthAxisConstructorOptions = {
    startX: number;
    startY?: number;
    startZ: number;
    minZ: number;
    tools: Tool[];
    xOffset?: number;
    zOffset?: number;
    fourth_axis_speed?: number;
};
export default class FourthAxisHelper {
    #private;
    startX: number;
    startY: number;
    startZ: number;
    minZ: number;
    maxZ: number;
    xOffset: number;
    zOffset: number;
    constructor({ startX, startY, startZ, minZ, tools, xOffset, zOffset, fourth_axis_speed }: FourthAxisConstructorOptions);
    get x(): number;
    get y(): number;
    get z(): number;
    get current_tool(): Tool;
    move(x_position?: number, y_position?: number, z_position?: number, degrees?: number): void;
    moveRelative(x_relative?: number, y_relative?: number, z_relative?: number, degrees?: number): void;
    setX(xVal: number): void;
    setXRelative(relAmount: number): void;
    moveX(xVal: number): void;
    moveXRapid(xVal: number): void;
    moveXWithRotation(xVal: number, degrees: number): void;
    moveXRelative(relAmount: number): void;
    moveXRelativeRapid(relAmount: number): void;
    moveXRelativeWithRotation(relAmount: number, degrees: number): void;
    setY(yVal: number): void;
    setYRelative(relAmount: number): void;
    moveY(yVal: number): void;
    moveYRapid(yVal: number): void;
    moveYWithRotation(yVal: number, degrees: number): void;
    moveYRelative(relAmount: number): void;
    moveYRelativeRapid(relAmount: number): void;
    moveYRelativeWithRotation(relAmount: number, degrees: number): void;
    resetY(): void;
    moveXYWithRotation(xVal: number, yVal: number, degrees: number): void;
    moveXYRelativeWithRotation(relXAmount: number, relYAmount: number, degrees: number): void;
    setZ(zVal: number): void;
    setZRelative(relAmount: number): void;
    moveZ(zVal: number): void;
    moveZRelative(relAmount: number): void;
    resetZ(): void;
    saveStartZ(newStartZ?: number): void;
    stepDown(step_amount?: number): void;
    rotate4thAxis(degrees: number, speed?: number): void;
    rotate4thAxisRapid(degrees: number): void;
    cutRingAtLength(cut_end?: 'head' | 'tail' | 'center', cut_x_position?: number, end_z?: number, reset_cut_end_offset?: boolean): void;
    millToRadius(min_x: number, max_x: number, radius: number, x_step_amount?: number): void;
    clockwiseArc(relative_end_x: number, relative_end_y: number, relative_center_x: number, relative_center_y: number): void;
    counterClockwiseArc(relative_end_x: number, relative_end_y: number, relative_center_x: number, relative_center_y: number): void;
    addCustomGCode(custom_code: string): void;
    cutHole(radius: number, hole_x_position?: number, end_z?: number): void;
    flatten(min_x: number, max_x: number, y_deviation: number, end_z: number, step_amount?: number): void;
    peckPlunge(step: number, x_position?: number, y_position?: number, end_z?: number, feed_rate?: number): void;
    plunge(x_position?: number, y_position?: number, end_z?: number, feed_rate?: number): void;
    toolChange(toolNum?: number): void;
    generateGCode(file: string): void;
}
//# sourceMappingURL=fourthAxisHelper.d.ts.map